install:
- ps: >-
    Install-PackageProvider -Name NuGet -Force
    
    Install-Module -Name PSScriptAnalyzer -Force
    
    Install-Module -Name Pester -Force
build: on
test_script:
- ps: >- 
    .\CI\Start_CI.ps1
